# data trasformation (reshape, reformat and reorder the data)

In [3]:
import pandas as pd
df = pd.read_csv('D:/Code Field Offline/datasets/bollywood.csv')
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

### Sorting (sorting column wise single/multiple also reseting index and sorting index)

In [4]:
df.sort_values('Year')

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
7,Hrithik Roshan,War,2019,Action,475,6.5
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [6]:
df.sort_values('Year', ascending=False)

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
2,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [13]:
df.sort_values(['Year', 'IMDb'], ascending=False) # multiple columns

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
7,Hrithik Roshan,War,2019,Action,475,6.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [15]:
dff = df.sort_values(['Year', 'IMDb'], ascending=False).copy()
dff.reset_index()

,index,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
2,3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
3,11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
4,8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
5,7,Hrithik Roshan,War,2019,Action,475,6.5
6,5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
7,6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
8,4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
9,10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
10,1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
11,2,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [22]:
dff.reset_index(drop=True) # this will drop the backup old index column

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
2,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
3,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
4,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
5,Hrithik Roshan,War,2019,Action,475,6.5
6,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
7,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
8,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
9,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
10,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
11,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [23]:
dff.reset_index(drop=True, inplace=True) # inplace = true will change the original dff
dff

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
2,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
3,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
4,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
5,Hrithik Roshan,War,2019,Action,475,6.5
6,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
7,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
8,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
9,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
10,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
11,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [26]:
# to show you sort_index we are doing this
a = df.sort_values('IMDb').copy()
a

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
2,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [27]:
a.sort_index()

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [28]:
dff

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
2,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
3,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
4,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
5,Hrithik Roshan,War,2019,Action,475,6.5
6,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
7,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
8,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
9,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
10,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
11,Aamir Khan,Dangal,2016,Biography,2024,8.4

### Ranking

In [39]:
dff['top movies'] = dff['IMDb'].rank(ascending=False) # if you won't do ascening = false the less imdb will get rank 1
dff

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,top movies
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0
1,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,11.0
2,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,12.0
3,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3.0
4,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.5
5,Hrithik Roshan,War,2019,Action,475,6.5,8.0
6,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2.0
7,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4.0
8,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.5
9,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,9.0
10,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,10.0
11,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0

In [42]:
dff.sort_values('top movies') # see index 4 and 8 it has 6.5 rank but it is tie 
# if you don't want to have a float rank you and add an attribute in the rank(method='dense') then it will us a integer no only

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,top movies
11,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0
6,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2.0
3,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3.0
7,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4.0
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0
4,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.5
8,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.5
5,Hrithik Roshan,War,2019,Action,475,6.5,8.0
9,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,9.0
10,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,10.0
1,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,11.0
2,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,12.0

#### renaming a column and reording a column ( I don't think this is most important thing out there so fuck this)