In [2]:
# Data pre processing (using string methods, type casting, using funtions, etc)

In [3]:
import pandas as pd

# random things

In [77]:
df = pd.read_csv('D:/Code Field Offline/datasets/tips.csv')
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    str
 3   smoker      244 non-null    str
 4   day         244 non-null    str
 5   time        244 non-null    str
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), str(4)
memory usage: 17.3 KB

In [7]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
239    False
240    False
241    False
242    False
243    False
Length: 244, dtype: bool

In [39]:
# in with we are finding which one row is dupliacated
for i in range(len(df.duplicated())):
    if df.duplicated()[i] == True:
        print(i)
        print(df.loc[i])

202
total_bill      13.0
tip              2.0
sex           Female
smoker           Yes
day             Thur
time           Lunch
size               2
Name: 202, dtype: object

In [40]:
# we'll also see that with row is duplicate of this actully

In [44]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

# strings methods in pandas

In [57]:
# stirngs methods 
# we use strings methods in columns
df['time'].str.upper()

0      DINNER
1      DINNER
2      DINNER
3      DINNER
4      DINNER
        ...
239    DINNER
240    DINNER
241    DINNER
242    DINNER
243    DINNER
Name: time, Length: 244, dtype: str

In [51]:
df['sex'].str.contains('female', case=False)

0       True
1      False
2      False
3      False
4       True
       ...
239    False
240     True
241    False
242    False
243     True
Name: sex, Length: 244, dtype: bool

In [52]:
df['sex'].str.split('a')

0      [Fem, le]
1        [M, le]
2        [M, le]
3        [M, le]
4      [Fem, le]
         ...
239      [M, le]
240    [Fem, le]
241      [M, le]
242      [M, le]
243    [Fem, le]
Name: sex, Length: 244, dtype: object

In [54]:
type(df['sex'].str.split('a')[0]) # this is a python list

list

# type casting

In [58]:
type(df['size'][0]) # this is an numpy int

numpy.int64

In [87]:
# we'll typecast into float
# for that we'll just create a copy of the dataframe
df2 = df.copy()
df2['size'] = df2['size'].astype(float)
df2

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner   2.0
1         10.34  1.66    Male     No   Sun  Dinner   3.0
2         21.01  3.50    Male     No   Sun  Dinner   3.0
3         23.68  3.31    Male     No   Sun  Dinner   2.0
4         24.59  3.61  Female     No   Sun  Dinner   4.0
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner   3.0
240       27.18  2.00  Female    Yes   Sat  Dinner   2.0
241       22.67  2.00    Male    Yes   Sat  Dinner   2.0
242       17.82  1.75    Male     No   Sat  Dinner   2.0
243       18.78  3.00  Female     No  Thur  Dinner   2.0

[244 rows x 7 columns]

In [62]:
# standard template to type conversion
# df["Category"] = df["Category"].astype(type)

# there is one for for data that can be done later

# appling function in pandas dataframe

In [81]:
# so for exmple you want to show that the tip is good enough or not
# so that let say that I decided that the tip more them the avarage tip is good and less then is bad
# for that I want to make a new column and write the good and bad thing
df2['tip rating'] = df2['tip'].apply(lambda tip: 'enough' if tip >= df['tip'].mean() else 'not enough')
df2

     total_bill   tip     sex smoker   day    time  size  tip rating
0         16.99  1.01  Female     No   Sun  Dinner   2.0  not enough
1         10.34  1.66    Male     No   Sun  Dinner   3.0  not enough
2         21.01  3.50    Male     No   Sun  Dinner   3.0      enough
3         23.68  3.31    Male     No   Sun  Dinner   2.0      enough
4         24.59  3.61  Female     No   Sun  Dinner   4.0      enough
..          ...   ...     ...    ...   ...     ...   ...         ...
239       29.03  5.92    Male     No   Sat  Dinner   3.0      enough
240       27.18  2.00  Female    Yes   Sat  Dinner   2.0  not enough
241       22.67  2.00    Male    Yes   Sat  Dinner   2.0  not enough
242       17.82  1.75    Male     No   Sat  Dinner   2.0  not enough
243       18.78  3.00  Female     No  Thur  Dinner   2.0      enough

[244 rows x 8 columns]

In [89]:
sexmap = {'Female': 'F' , 'Male': 'M'}
df2['sex'] = df2['sex'].map(sexmap)
df2

     total_bill   tip sex smoker   day    time  size
0         16.99  1.01   F     No   Sun  Dinner   2.0
1         10.34  1.66   M     No   Sun  Dinner   3.0
2         21.01  3.50   M     No   Sun  Dinner   3.0
3         23.68  3.31   M     No   Sun  Dinner   2.0
4         24.59  3.61   F     No   Sun  Dinner   4.0
..          ...   ...  ..    ...   ...     ...   ...
239       29.03  5.92   M     No   Sat  Dinner   3.0
240       27.18  2.00   F    Yes   Sat  Dinner   2.0
241       22.67  2.00   M    Yes   Sat  Dinner   2.0
242       17.82  1.75   M     No   Sat  Dinner   2.0
243       18.78  3.00   F     No  Thur  Dinner   2.0

[244 rows x 7 columns]

In [92]:
df2['smoker'] = df2['smoker'].replace({'No': 0, 'Yes':1})
df2

     total_bill   tip sex smoker   day    time  size
0         16.99  1.01   F      0   Sun  Dinner   2.0
1         10.34  1.66   M      0   Sun  Dinner   3.0
2         21.01  3.50   M      0   Sun  Dinner   3.0
3         23.68  3.31   M      0   Sun  Dinner   2.0
4         24.59  3.61   F      0   Sun  Dinner   4.0
..          ...   ...  ..    ...   ...     ...   ...
239       29.03  5.92   M      0   Sat  Dinner   3.0
240       27.18  2.00   F      1   Sat  Dinner   2.0
241       22.67  2.00   M      1   Sat  Dinner   2.0
242       17.82  1.75   M      0   Sat  Dinner   2.0
243       18.78  3.00   F      0  Thur  Dinner   2.0

[244 rows x 7 columns]

In [93]:
# so we saw there main fucntion lambda ( we an also use a user define fuction ), map and replace 
# NOTE: map can repalce all value element-wise and replace can replace spcific elements as well