**Three topics covered in this:**
* melt and pivot
* aggregration and grouping
* merging and joining

# Melt and Pivot 
wide to long and long to wide

In [2]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Aman", "Riya", "Karan", "Simran"],
    "Math": [85, 92, 78, 88],
    "Science": [90, 89, 82, 94],
    "English": [78, 95, 80, 87]
})

df

     Name  Math  Science  English
0    Aman    85       90       78
1    Riya    92       89       95
2   Karan    78       82       80
3  Simran    88       94       87

### Melt
**Syntax:**
```python
df.melt(id_vars=None, value_vars=None, var_name=None, value_name="value", col_level=None)
```

**Parameters:**
* **id_vars:** The columns that you want to keep fixed (these columns will remain as identifiers).
* **value_vars:** The columns you want to unpivot (the ones you want to "melt" into a single column).
* **var_name:** The name to use for the new column that will contain the names of the melted columns (default is 'variable').
* **value_name:** The name to use for the new column that will contain the values from the melted columns (default is 'value').
* **col_level:** Used for multi-level column DataFrames.

In [6]:
df.melt(id_vars='Name', value_vars=['Math','Science','English'], var_name='Subjects', value_name='Marks')

      Name Subjects  Marks
0     Aman     Math     85
1     Riya     Math     92
2    Karan     Math     78
3   Simran     Math     88
4     Aman  Science     90
5     Riya  Science     89
6    Karan  Science     82
7   Simran  Science     94
8     Aman  English     78
9     Riya  English     95
10   Karan  English     80
11  Simran  English     87

In [10]:
dff = df.melt(id_vars='Name', value_vars=['Math','Science','English'], var_name='Subjects', value_name='Marks').copy()

### Pivot
**Syntax:**
```python
df.pivot(index=None, columns=None, values=None)
```
**Parameters:**
* **index:** The column whose unique values will become the rows of the new DataFrame.
* **columns:** The column whose unique values will become the columns of the new DataFrame.
* **values:** The column whose values will fill the new DataFrame. These will become the actual data (values in the table).
> *and if you find multiple values for the same then pivot can throw error in that case you can use `pivot_table()` method that works as same as this and the reason it gives you a attribute that can adjust the duplicate value by the replacing it with mean or max or min or any condition applied and that is:*
* **aggfunc:** This will replace the duplicate value with a single value as per the condition (mean, min, max, etc)

In [11]:
dff.pivot(index='Name', columns='Subjects', values='Marks')

Subjects  English  Math  Science
Name
Aman           78    85       90
Karan          80    78       82
Riya           95    92       89
Simran         87    88       94

# Aggregration and Grouping
grouping data

In [29]:
df = pd.read_csv('D:/Code Field/the_winter_revision_2026/datasets/Iris.csv')
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [12]:
df['Species'].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [13]:
df.groupby('Species')['SepalLengthCm'].agg('mean')

Species
Iris-setosa        5.006
Iris-versicolor    5.936
Iris-virginica     6.588
Name: SepalLengthCm, dtype: float64

In [15]:
df.groupby('Species')[['SepalLengthCm', 'SepalWidthCm']].agg('mean')

                 SepalLengthCm  SepalWidthCm
Species
Iris-setosa              5.006         3.418
Iris-versicolor          5.936         2.770
Iris-virginica           6.588         2.974

In [16]:
df.groupby('Species')[['SepalLengthCm', 'SepalWidthCm']].agg(['min', 'max'])

                SepalLengthCm      SepalWidthCm
                          min  max          min  max
Species
Iris-setosa               4.3  5.8          2.3  4.4
Iris-versicolor           4.9  7.0          2.0  3.4
Iris-virginica            4.9  7.9          2.2  3.8

In [21]:
df.groupby('Species')['SepalLengthCm'].agg(
    avg_lenght = 'mean', 
    max_lenght = 'max',
    min_lenght = 'min'
)

                 avg_lenght  max_lenght  min_lenght
Species
Iris-setosa           5.006         5.8         4.3
Iris-versicolor       5.936         7.0         4.9
Iris-virginica        6.588         7.9         4.9

## Transform vs Aggregate vs Filter

| Operation | Returns | When to Use | 
|-----------| -------- |-------------|
| `.aggregate()` | Single value per group	| Summary (like mean) | 
| `.transform()` | Same shape as original	| Add new column based on group |
| `.filter()`	| Subset of rows | Keep/discard whole groups | 


`.transform()` Example:
```python
df["Team Avg"] = df.groupby("Team")["Salary"].transform("mean")
```
Now each row gets its team average — great for comparisons!


`.filter()` Example:
```python
df.groupby("Team").filter(lambda x: x["Salary"].mean() > 80)
```
Only keeps teams with average score > 80.

In [30]:
# sadly with don't have a good use case of transform and filter in this dataframe but we'll use these two in future for sure

**Summary**
* `.groupby()` helps you summarize large datasets by category
* Use `mean()`, `sum()`, `count()`, `.agg()` for custom metrics
* `.transform()` adds values back to original rows
* `.filter()` keeps only groups that meet conditions

# Merging and Joining

In [34]:
# so I think we can do this while making project 
# we use mainly two things
# pd.merge()
# pd.concat()