**Three topics covered in this:**
* melt and pivot
* aggregration and grouping
* merging and grouping

# Melt and Pivot 
wide to long and long to wide

In [4]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Aman", "Riya", "Karan", "Simran"],
    "Math": [85, 92, 78, 88],
    "Science": [90, 89, 82, 94],
    "English": [78, 95, 80, 87]
})

df

     Name  Math  Science  English
0    Aman    85       90       78
1    Riya    92       89       95
2   Karan    78       82       80
3  Simran    88       94       87

### Melt
**Syntax:**
```python
df.melt(id_vars=None, value_vars=None, var_name=None, value_name="value", col_level=None)
```

**Parameters:**
* **id_vars:** The columns that you want to keep fixed (these columns will remain as identifiers).
* **value_vars:** The columns you want to unpivot (the ones you want to "melt" into a single column).
* **var_name:** The name to use for the new column that will contain the names of the melted columns (default is 'variable').
* **value_name:** The name to use for the new column that will contain the values from the melted columns (default is 'value').
* **col_level:** Used for multi-level column DataFrames.

In [6]:
df.melt(id_vars='Name', value_vars=['Math','Science','English'], var_name='Subjects', value_name='Marks')

      Name Subjects  Marks
0     Aman     Math     85
1     Riya     Math     92
2    Karan     Math     78
3   Simran     Math     88
4     Aman  Science     90
5     Riya  Science     89
6    Karan  Science     82
7   Simran  Science     94
8     Aman  English     78
9     Riya  English     95
10   Karan  English     80
11  Simran  English     87

In [10]:
dff = df.melt(id_vars='Name', value_vars=['Math','Science','English'], var_name='Subjects', value_name='Marks').copy()

### Pivot
**Syntax:**
```python
df.pivot(index=None, columns=None, values=None)
```
**Parameters:**
* **index:** The column whose unique values will become the rows of the new DataFrame.
* **columns:** The column whose unique values will become the columns of the new DataFrame.
* **values:** The column whose values will fill the new DataFrame. These will become the actual data (values in the table).
> *and if you find multiple values for the same then pivot can throw error in that case you can use `pivot_table()` method that works as same as this and the reason it gives you a attribute that can adjust the duplicate value by the replacing it with mean or max or min or any condition applied and that is:*
* **aggfunc:** This will replace the duplicate value with a single value as per the condition (mean, min, max, etc)

In [11]:
dff.pivot(index='Name', columns='Subjects', values='Marks')

Subjects  English  Math  Science
Name
Aman           78    85       90
Karan          80    78       82
Riya           95    92       89
Simran         87    88       94

# Aggregration and Grouping